#!/usr/bin/env bash

if [ -z "$PETSC_DIR" ] || [ -z "$PETSC_ARCH" ]; then 
  echo -e "\033[1;33mERROR\033[0m: Petsc env vars unset!"
  exit 2
fi


use_debugger=false
use_cuda_binary=false
use_log=false

for arg in "$@"; do
    case "$arg" in
        "-d") use_debugger=true ;;
        "-l") use_log=true ;;
        "-c") use_cuda_binary=true
    esac
done

PATH="$PATH":"$PETSC_DIR/$PETSC_ARCH/lib"
DATAFILESPATH=${DATAFILESPATH:-"$PETSC_DIR/../datafiles"}
executable_root="bin/$PETSC_ARCH"

args="-options_file opts/ex79.opt"
load_dir="-load_dir ${DATAFILESPATH}/matrices/hpddm/GENEO"
mpiexec=${PETSCMPIEXEC:-"$PETSC_DIR/$PETSC_ARCH/bin/mpiexec"}


executable_name='ex79'
debugger_args=''
log_args=''
nsize_in=${nsize:-4}

if [ "$use_log" == true ]; then
  log_args="-log_view"
fi
if [ "$use_debugger" == true ]; then
  debugger_args="-stop_for_debugger"
fi
# if [ "$use_cuda_binary" == true ]; then
#   executable_name="noiseless_gpu"
# fi

debugger_available=false
debugger_exec=''

if [ "$use_debugger" == true  ];then
  if command -v lldb >/dev/null 2>&1; then
    debugger_exec="lldb"
  elif command -v gdb >/dev/null 2>&1; then
    debugger_exec="gdb"
  else
    echo "No supported debugger found!"
  fi
fi

if [ "$use_debugger" == true  ];then
  if ! [ -e "temp_output" ]; then
    ${mpiexec} -n ${nsize_in} ${executable_root}/${executable_name} ${args} ${load_dir} ${debugger_args} ${log_args} > temp_output &
  else
    echo 'Temp output exists.. maybe another lauch is already in progress'
  fi
  sleep 1.0 
  pid=$(ps aux | rg $USER | rg "bin\/$PETSC_ARCH\/$executable_name" | awk 'NR>1{print $2}' |sort -u | head -n1)
  if ! [ -z $(ps aux | grep -v grep| grep $pid) ]; then 
    $debugger_exec -p $pid
    sleep 0.5
    cat temp_output
    rm temp_output
  else
    echo 'Could not find process to attach to!'
  fi
else 
  ${mpiexec} -n ${nsize_in} ${executable_root}/${executable_name} ${args} ${load_dir} ${debugger_args} ${log_args}
fi

