#!/bin/bash 

output_file=timings.dat
number_of_runs=${1:-10}

if [ -f "$output_file" ]; then 
  mv "$output_file" "$output_file.old"
fi


for i in $(seq 1 "$number_of_runs"); do
  ./run_noiseless -l -c | rg 'Summary' -A3 | rg Main | awk '{print $4}'| tee -a $output_file;
done
